# - [ RRCore Configuration File ]

#Language Settings
#Languages Available: eng
lang: "eng"

#Factions System Settings
factions:
    #Whether or not the factions system (/f) should be enabled
    enabled: true
    